import '../domain/i_trekking_repository.dart';
import '../domain/trekking_location.dart';

class MockTrekkingRepository implements ITrekkingRepository {
  @override
  Future<List<TrekkingLocation>> getLocations() async {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 500));

    return const [
      TrekkingLocation(
        id: '1',
        name: 'Fansipan Peak',
        distance: '12.5 km',
        difficulty: TrekkingDifficulty.hard,
        icon: '🏔️',
        latitude: 22.3033,
        longitude: 103.7753,
      ),
      TrekkingLocation(
        id: '2',
        name: 'Cat Cat Village',
        distance: '2.0 km',
        difficulty: TrekkingDifficulty.easy,
        icon: '🏘️',
        latitude: 22.3311,
        longitude: 103.8290,
      ),
      TrekkingLocation(
        id: '3',
        name: 'Muong Hoa Valley',
        distance: '8.5 km',
        difficulty: TrekkingDifficulty.moderate,
        icon: '🌾',
        latitude: 22.2961,
        longitude: 103.8942,
      ),
      TrekkingLocation(
        id: '4',
        name: 'Silver Waterfall',
        distance: '15.0 km',
        difficulty: TrekkingDifficulty.easy,
        icon: '🌊',
        latitude: 22.3614,
        longitude: 103.7781,
      ),
      TrekkingLocation(
        id: '5',
        name: 'Love Waterfall',
        distance: '14.0 km',
        difficulty: TrekkingDifficulty.moderate,
        icon: '💖',
        latitude: 22.3486,
        longitude: 103.7711,
      ),
      TrekkingLocation(
        id: '6',
        name: 'Ham Rong Mountain',
        distance: '1.5 km',
        difficulty: TrekkingDifficulty.easy,
        icon: '🐉',
        latitude: 22.3382,
        longitude: 103.8475,
      ),
      TrekkingLocation(
        id: '7',
        name: 'Ta Phin Village',
        distance: '12.0 km',
        difficulty: TrekkingDifficulty.moderate,
        icon: '🧣',
        latitude: 22.3850,
        longitude: 103.8760,
      ),
      TrekkingLocation(
        id: '8',
        name: 'Lao Chai Village',
        distance: '7.0 km',
        difficulty: TrekkingDifficulty.easy,
        icon: '🛖',
        latitude: 22.3038,
        longitude: 103.8542,
      ),
      TrekkingLocation(
        id: '9',
        name: 'Ta Van Village',
        distance: '10.0 km',
        difficulty: TrekkingDifficulty.moderate,
        icon: '🍛',
        latitude: 22.3000,
        longitude: 103.8800,
      ),
      TrekkingLocation(
        id: '10',
        name: 'Ban Ho Village',
        distance: '20.0 km',
        difficulty: TrekkingDifficulty.hard,
        icon: '🎣',
        latitude: 22.2386,
        longitude: 103.9514,
      ),
      TrekkingLocation(
        id: '11',
        name: 'Sin Chai Village',
        distance: '4.0 km',
        difficulty: TrekkingDifficulty.easy,
        icon: '🌿',
        latitude: 22.3389,
        longitude: 103.8053,
      ),
      TrekkingLocation(
        id: '12',
        name: 'O Quy Ho Pass',
        distance: '16.0 km',
        difficulty: TrekkingDifficulty.hard,
        icon: '☁️',
        latitude: 22.3533,
        longitude: 103.7667,
      ),
      TrekkingLocation(
        id: '13',
        name: 'Heaven Gate',
        distance: '17.0 km',
        difficulty: TrekkingDifficulty.moderate,
        icon: '⛩️',
        latitude: 22.3550,
        longitude: 103.7600,
      ),
      TrekkingLocation(
        id: '14',
        name: 'Seo My Ty Reservoir',
        distance: '25.0 km',
        difficulty: TrekkingDifficulty.hard,
        icon: '🛶',
        latitude: 22.2500,
        longitude: 103.8500,
      ),
      TrekkingLocation(
        id: '15',
        name: 'Nam Cang Village',
        distance: '35.0 km',
        difficulty: TrekkingDifficulty.hard,
        icon: '🪵',
        latitude: 22.1800,
        longitude: 104.0200,
      ),
      TrekkingLocation(
        id: '16',
        name: 'Giang Ta Chai',
        distance: '12.0 km',
        difficulty: TrekkingDifficulty.moderate,
        icon: '🚶',
        latitude: 22.2900,
        longitude: 103.9100,
      ),
      TrekkingLocation(
        id: '17',
        name: 'Sapa Ancient Rock Field',
        distance: '11.0 km',
        difficulty: TrekkingDifficulty.easy,
        icon: '🪨',
        latitude: 22.2883,
        longitude: 103.9033,
      ),
      TrekkingLocation(
        id: '18',
        name: 'Hau Thao Village',
        distance: '8.0 km',
        difficulty: TrekkingDifficulty.moderate,
        icon: '⛅',
        latitude: 22.3150,
        longitude: 103.9050,
      ),
      TrekkingLocation(
        id: '19',
        name: 'Suoi Thau Cave',
        distance: '14.5 km',
        difficulty: TrekkingDifficulty.hard,
        icon: '🦇',
        latitude: 22.4100,
        longitude: 103.8600,
      ),
      TrekkingLocation(
        id: '20',
        name: 'Ma Tra Village',
        distance: '5.0 km',
        difficulty: TrekkingDifficulty.easy,
        icon: '🌽',
        latitude: 22.3550,
        longitude: 103.8650,
      ),
      TrekkingLocation(
        id: '21',
        name: 'Cau May Bridge',
        distance: '10.5 km',
        difficulty: TrekkingDifficulty.easy,
        icon: '🌉',
        latitude: 22.3020,
        longitude: 103.8770,
      ),
      TrekkingLocation(
        id: '22',
        name: 'Den Thượng Temple',
        distance: '3.0 km',
        difficulty: TrekkingDifficulty.easy,
        icon: '🕍',
        latitude: 22.3450,
        longitude: 103.8400,
      ),
      TrekkingLocation(
        id: '23',
        name: 'Fansipan Legend Station',
        distance: '3.5 km',
        difficulty: TrekkingDifficulty.moderate,
        icon: '🚠',
        latitude: 22.3320,
        longitude: 103.8230,
      ),
      TrekkingLocation(
        id: '24',
        name: 'Thanh Kim Village',
        distance: '22.0 km',
        difficulty: TrekkingDifficulty.hard,
        icon: '🐃',
        latitude: 22.2200,
        longitude: 103.9300,
      ),
      TrekkingLocation(
        id: '25',
        name: 'Bản Khoang Village',
        distance: '18.0 km',
        difficulty: TrekkingDifficulty.moderate,
        icon: '🍄',
        latitude: 22.4000,
        longitude: 103.7800,
      ),
      TrekkingLocation(
        id: '26',
        name: 'Tả Giàng Phình',
        distance: '28.0 km',
        difficulty: TrekkingDifficulty.hard,
        icon: '⛰️',
        latitude: 22.4500,
        longitude: 103.7500,
      ),
      TrekkingLocation(
        id: '27',
        name: 'Sapa Market',
        distance: '0.5 km',
        difficulty: TrekkingDifficulty.easy,
        icon: '🛍️',
        latitude: 22.3350,
        longitude: 103.8450,
      ),
    ];
  }
}
